### ISSUE TITLE
godot-lib Feature requests

### ISSUE THREAD

**Issue by GeorgeS2019** [RhubarbVR/LibGodotSharp#4]
#### 28thMarch2023 Update

[LibGodot with GDExtension](https://github.com/godotengine/godot/pull/72883)

=======================================
Since it will be a while before [godot-lib](https://github.com/RhubarbVR/godot-lib) would be merged, this issue is to feedback and track feature requests related to godot-lib.

- [ ] Collect a list of **ToDo** or **Yet-To-Implement features** exposed through the Godot-Lib for c# 
- [ ] [Making Advanced GUI Applications with Godot](https://medium.com/swlh/what-makes-godot-engine-great-for-advance-gui-applications-b1cfb941df3b)

**Comment by Airyzz** [comment]
As I mentioned on the godot pull request, it would be great to be able to pass a custom opengl context to render to, or provide some other way of rendering to a texture, such that the godot display can be embedded inside other applications.

I think this would also benefit from a way to inject mouse/keyboard/touch inputs via code, so that for example, if I am creating a widget in flutter which displays the rendered texture, if I touch a point on that widget I can transfer that input back to godot.

**Comment by Faolan-Rad** [comment]
You can inject mouse/keyboard/touch input into a view port for example this is done in rhubarb [Ref](https://github.com/RhubarbVR/RhubarbVR/blob/507d291fecb5577b0f5e817bd64e82d14168aac0/RhubarbGodot/Bindings/ComponentLinking/ViewportLink.cs#L70)

Now for render context I do want to do that because I plan to integrate lib VLC into rhubarb

**Comment by GeorgeS2019** [comment]
@Faolan-Rad  

Iphone version
https://github.com/migueldeicaza/SwiftGodot

https://github.com/RhubarbVR/LibGodotSharp/assets/49812372/bfaad261-5513-4d4c-9f24-85664e4645b5

**Comment by mikejohnstn** [comment]
I'm also very interested in using libgodot with an offscreen rendering context. After spending some time researching the state of things, I thought I'd share what I found in case it helps (or in case I got some things wrong).

- libgodot itself is slated for a 4.x Godot release, but the PR seems stalled I think?
- libgodot is already being used for RhubarbVR
- it's also now powering [SwiftGodot](https://github.com/migueldeicaza/SwiftGodot)
- people seem to be able to follow these examples for their own purposes (including me, got it working with Rust)
- there's a proposal by Carinou for offscreen rendering in Godot but it doesn't seem to have much traction: https://github.com/godotengine/godot-proposals/issues/5790
- Carinou links to a Vulkan sample that achieves offscreen rendering: https://github.com/SaschaWillems/Vulkan/blob/master/examples/renderheadless/renderheadless.cpp
- there's a related proposal by reduz for embedding a game view inside the editor, where he mentions using Vulkan extensions to do this: https://github.com/godotengine/godot-proposals/issues/7213
- I assume the community will focus on the embedded editor use case first, but maybe that work could help libgodot as well?

In the meantime, I found [one example of someone using a workaround](https://ask.godotengine.org/141103/normal-rendering-without-game-window-for-ai-training?show=141103#q141103) for offscreen rendering where they continuously render the viewport to a JPG buffer and send it elsewhere manually, but this still seems to require a window rendering in the background.

If anyone has any other updates / corrections / suggestions to move this forward, I'd love to hear!

**Comment by GeorgeS2019** [comment]
@mikejohnstn 

We need to give @Faolan-Rad more Love
